package com.dao;

import java.util.List;

import com.pojo.Book;

public interface BookMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int insert(Book record);

	List<Book> selectByPage(Integer startrecord, Integer pagecount);

	List<Book> selectByPageFilter(Integer startrecord, Integer pagecount, String category, String status,
			Integer userid);

	List<Book> selectByDescending(Integer record);

	List<Book> selectByUserPage(Integer userid, Integer startrecord, Integer pagecount,String category,String status);

	int selectCount();

	int selectCountFilter(String category, String status, Integer userid);

	int selectCountByUser(Integer userid, String category, String status);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int insertSelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	Book selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_book
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Book record);
}