package com.dao;

import java.util.List;

import org.apache.ibatis.type.IntegerTypeHandler;

import com.pojo.Borrow;

public interface BorrowMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	int insert(Borrow record);

	int selectMaxOrder();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	int insertSelective(Borrow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	Borrow selectByPrimaryKey(Integer id);

	List<Borrow> selectByBook(Integer id);

	List<Borrow> selectByUser(Integer id);
	
	List<Borrow> selectOutByUser(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Borrow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_borrow
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Borrow record);
}