package com.dao;

import java.util.List;

import com.pojo.Category;

public interface CategoryMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String category);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	int insert(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	int insertSelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	Category selectByPrimaryKey(String category);

	List<Category> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_category
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Category record);
}