package com.dao;

import java.util.List;

import com.pojo.Book;
import com.pojo.Location;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String location);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    Location selectByPrimaryKey(String location);
    
    List<Location> selectAllLocation();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Location record);
}