package com.dao;

import java.util.List;

import com.pojo.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Integer id);
	List<User> selectAll();

	User selectByInumber(String inumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	int updatePasswordByPrimaryKey(Integer userid, String password);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);
}